

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'MERCHANT',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  email_verified INTEGER DEFAULT 0,
  otp_code TEXT,
  otp_expires_at TEXT,
  available_balance NUMERIC DEFAULT 0,
  holding_balance NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  api_key TEXT UNIQUE NOT NULL,
  secret_key TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL DEFAULT 'Default Key',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS merchant_settings (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  webhook_url TEXT DEFAULT '',
  webhook_secret TEXT DEFAULT '',
  fee_type TEXT DEFAULT 'UNIQUE_CODE',
  fee_value NUMERIC DEFAULT 0,
  fee_bearer TEXT DEFAULT 'CUSTOMER',
  payout_type TEXT DEFAULT '',
  payout_provider TEXT DEFAULT '',
  payout_name TEXT DEFAULT '',
  payout_number TEXT DEFAULT '',
  payout_updated_at TEXT DEFAULT '',
  telegram_bot_token TEXT DEFAULT '',
  telegram_chat_id TEXT DEFAULT '',
  telegram_notif_active INTEGER DEFAULT 1,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS webhook_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  order_id TEXT NOT NULL,
  url TEXT NOT NULL,
  payload TEXT NOT NULL,
  response_status INTEGER DEFAULT 0,
  response_body TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transactions (
  order_id TEXT PRIMARY KEY,
  user_id BIGINT DEFAULT 1,
  base_amount BIGINT NOT NULL,
  unique_code INTEGER NOT NULL,
  fee_type TEXT DEFAULT 'UNIQUE_CODE',
  fee_amount BIGINT DEFAULT 0,
  fee_bearer TEXT DEFAULT 'CUSTOMER',
  total_amount BIGINT NOT NULL,
  net_amount BIGINT DEFAULT 0,
  customer_name TEXT,
  note TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  payment_url TEXT,
  dynamic_qris TEXT,
  qr_code_data_url TEXT,
  tx_id TEXT,
  is_released INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  paid_at TIMESTAMPTZ,
  expired_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS withdrawals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount BIGINT NOT NULL,
  fee BIGINT NOT NULL DEFAULT 5000,
  net_amount BIGINT NOT NULL,
  account_type TEXT NOT NULL,
  account_name TEXT NOT NULL,
  account_number TEXT NOT NULL,
  account_provider TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  note TEXT DEFAULT '',
  admin_note TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_transactions_total_amount ON transactions(total_amount);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_user ON withdrawals(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON withdrawals(status);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE withdrawals ENABLE ROW LEVEL SECURITY;

ALTER TABLE users ADD COLUMN IF NOT EXISTS available_balance NUMERIC DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS holding_balance NUMERIC DEFAULT 0;

